version: "3.1"

networks:
  app-tier:
    driver: bridge
services:
  mysql:
    networks:
      - app-tier
    image: mysql
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=woungsub123
      - MYSQL_USER=woungsub
      - MYSQL_PASSWORD=woungsub123
      - MYSQL_DATABASE=gooutdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    networks:
      - app-tier
    image: redis
    container_name: redis_container
    restart: always
    ports:
      - "6397:6397"
  app:
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile
    image: bus3013/goout-backend-api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    restart: always
    ports:
      - "80:3000"
    links:
      - mysql
    depends_on:
      - mysql
      - redis
